### PR TITLE
Show bound secret as a printer column

### PR DESCRIPTION
**Pull request by scothis**
```
kubectl get servicebinding
```

```
NAME                  SECRET                READY   REASON         AGE
spring-petclinic-db   spring-petclinic-db   True    ServiceBound   20m
```

Signed-off-by: Scott Andrews <andrewssc@vmware.com>

### CODE REVIEW

**Comment by baijum** [comment]
As per the current implementation, the name of the Secret is always the name of the ServiceBinidng resource, right?

**Comment by sadlerap** [comment]
@baijum It's supposed to be the name of the secret we fetched from the service.  [From the spec](https://github.com/servicebinding/spec/#service-binding):
> A `ServiceBinding` **SHOULD** reflect the secret projected into the workload as `.status.binding.name`.

**Comment by scothis** [comment]
@sadlerap that's correct. It's not a great example that they happen to be the same.

@baijum the `.spec.name` will default to `.metadata.name`, is that what you're thinking of?

**Comment by baijum** [comment]
@scothis @sadlerap Please ignore my comment. I got confused by the example given in the description.

**Review by baijum — APPROVED** [review]
LGTM

**Pull request merged**
